imuq:
  imu_rate: 100.0
  acc_noise: 0.05
  acc_bias_noise: 0.005
  acc_bias_std: 0.01
  gyr_noise: 0.005
  gyr_bias_noise: 0.0001
  gyr_bias_std: 0.0001
grid:
  cell_rows: 2
  cell_cols: 16
  nms: True
  max_score: 0.005
gicp:
  outer: 2
  inner: 3
  half_rows: 2
  cov_lambda: 1.0e-8
pano:
  rows: 256
  cols: 1024
  vfov: 0.0
  max_cnt: 20
  range_ratio: 0.05
