grid:
  cell_rows: 2
  cell_cols: 16
  nms: True
  max_score: 0.01
  half_rows: 2
  cov_lambda: 1e-6
icp:
  outer: 1
  inner: 3
pano:
  rows: 256
  cols: 1024
  hfov: 0.0
  max_cnt: 16
  range_ratio: 0.1
