imuq:
  buffer_size: 20
  imu_rate: 100.0
  acc_noise: 0.005
  acc_bias_noise: 0.001
  acc_bias_std: 0.05
  gyr_noise: 0.0005
  gyr_bias_noise: 0.0001
  gyr_bias_std: 0.005
traj:
  use_acc: true
grid:
  cell_rows: 1
  cell_cols: 8
  max_curve: 0.1
  max_var: 0.1
  nms: true
gicp:
  outer: 2
  inner: 4
  half_rows: 2
  cov_lambda: 0.0
  min_eigval: 0.0
  imu_weight: 2.0
pano:
  rows: 256
  cols: 1024
  vfov: 0.0
  max_cnt: 20
  min_range: 0.5
  range_ratio: 0.1
  align_gravity: true
rigid: false
