imu:
  acc_noise: 0.001249
  acc_rand_walk: 0.000106
  gyr_noise: 0.000208
  gyr_rand_walk: 0.000004
grid:
  cell_rows: 2
  cell_cols: 16
  nms: True
  max_score: 0.01
gicp:
  outer: 2
  inner: 3
  half_rows: 2
  cov_lambda: 1e-6
pano:
  rows: 256
  cols: 1024
  vfov: 0.0
  max_cnt: 16
  range_ratio: 0.1
