imuq:
  buffer_size: 20
  imu_rate: 100.0
  acc_noise: 0.05
  acc_bias_noise: 0.005
  acc_bias_std: 0.01
  gyr_noise: 0.005
  gyr_bias_noise: 0.0002
  gyr_bias_std: 0.0002
grid:
  cell_rows: 2
  cell_cols: 8
  max_curve: 0.02
  max_var: 0.02
  nms: True
gicp:
  outer: 2
  inner: 3
  half_rows: 2
  cov_lambda: 1.0e-8
  min_eigval: 0.0
pano:
  rows: 256
  cols: 1024
  vfov: 0.0
  max_cnt: 20
  min_range: 0.5
  range_ratio: 0.1
  align_gravity: True
rigid: False
