grid:
  cell_rows: 2
  cell_cols: 16
  nms: True
  max_score: 0.01
match:
  half_rows: 2
  min_dist: 2.0
  cov_lambda: 1e-6
pano:
  rows: 256
  cols: 1024
  hfov: 0.0
  max_cnt: 10
  range_ratio: 0.1
